config/routes.rb
ClapApp::Application.routes.draw do
  resources :user
  resources :movies, :defaults => { :format => 'json' }
  match 'user/:id' => "Movies#show", :format => 'json'
  match 'movie/like/:id' => 'Movies#like'
  match 'movie/:id' => "Movies#show", :format => 'json'
  match 'movie/dislike/:id' => 'Movies#dislike'
  match 'movie/review/:id' => 'Movies#review'

end

app/models/like.rb
class Like < ActiveRecord::Base
	validates :user, :presence => true, :uniqueness => {:scope => :movie}
	validates :movie, :presence => true 
	belongs_to :movie
	belongs_to :user
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	validates :alloCineCode, :presence => true, :uniqueness =>true
	validates :title, :presence => true
	has_many :reviews
	has_many :users, :through => :reviews
	has_many :users, :through => :likes
	
end

app/models/review.rb
class Review < ActiveRecord::Base
	validates :user, :presence => true, :uniqueness => {:scope => :movie}
	validates :movie, :presence => true 
	belongs_to :movie
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, :presence => true, :uniqueness =>true, :length => { :minimum => 3}
	has_many :reviews
	has_many :movies, :through => :reviews
	has_many :movies, :through => :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # @@proxyUTC = 'http://proxyweb.utc.fr:3128';
  @@proxyUTC = nil;
  
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
	# @alloCineJson = JSON.parse(open("http://api.allocine.fr/rest/v3/movielist?partner=YW5kcm9pZC12M3M&count=25&filter=nowshowing&order=toprank&format=json").read)["feed"]
	@alloCineJson = JSON.parse(open("http://api.allocine.fr/rest/v3/movielist?partner=YW5kcm9pZC12M3M&count=40&filter=nowshowing&order=toprank&format=json&profile=small").read)["feed"]
	response = {}
	movies = []
	@alloCineJson["movie"].each{ |mv|
		movie=Movie.where(:alloCineCode => mv["code"]).first
		if !movie
			movie = Movie.create(:alloCineCode => mv["code"], :title=>mv["title"])
		end
		movieHash = {}
		movieHash["id"] = movie.id
		movieHash["code"] = movie["title"]
		movieHash["code"] = mv["title"]
		movieHash["title"] = mv["title"]
		movieHash["poster"] = mv["poster"]["href"]
		movies << movieHash
	}
	response["movies"] = movies

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: response }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
	# require 'net/http'
	require 'open-uri'
	require 'json'

    @movie = Movie.find(params[:id])
	response = {}
	@alloCineJson = JSON.parse(open("http://api.allocine.fr/rest/v3/movie?partner=YW5kcm9pZC12M3M&format=json&filter=movie&profile=small&mediafmt=mp4&code="+ @movie.alloCineCode.to_s, :proxy => @@proxyUTC).read)["movie"]
	response["title"]=@alloCineJson["title"]
	response["directors"]=@alloCineJson["castingShort"]["directors"]
	response["actors"]=@alloCineJson["castingShort"]["actors"]
	response["synopsisShort"]=@alloCineJson["synopsisShort"]
	response["releaseDate"]=@alloCineJson["release"]["releaseDate"]
	response["poster"]=@alloCineJson["poster"]["href"]
	response["runtime"]=@alloCineJson["runtime"]
	@trailerInfoJson = JSON.parse(open("http://api.allocine.fr/rest/v3/media?format=json&partner=aXBhZC12MQ&profile=small&mediafmt=mp4&code="+ @alloCineJson["trailer"]["code"].to_s).read)["media"]
	response["trailer"]=@trailerInfoJson["rendition"][0]["href"]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: response }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end
  
  def like
	@user = User.find(params[:userId])
	@movie = Movie.find(params[:id])
	like = Like.create(:user => @user, :movie=> @movie)
	render :action => 'show'
  end
  
  def review
	@user = User.find(params[:userId])
	@movie = Movie.find(params[:id])
	review = Review.create(:user => @user, :movie=> @movie, :content => params[:textContent])
	render :action => 'show'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  def signup
	@user = User.create()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClapApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alloCineCode %><br />
    <%= f.number_field :alloCineCode %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <tr>
    <th>Allocinecode</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td><%= movie.alloCineCode %></td>
    <td><%= movie.title %></td>
    <td><%= link_to 'Show', movie %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Allocinecode:</b>
  <%= @movie.alloCineCode %>
</p>

<p>
  <b>Title:</b>
  <%= @movie.title %>
</p>

<p>
  <b>Truc:</b>
  <%= @truc %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>